create database mashan;
use mashan;

drop table SMARO_E_luotong;
drop table JWF1562_xisha;
drop table JWF1418_cusha;
drop table JWF1312B_bingtiao;
drop table JWF1211_shumuan;

create table JWF1211_shumuan (
	record_id bigint not null auto_increment,	
	machineNo int,
	record_timestamp datetime,
	fixed_length int,
	raw_head_speed int,
	alarm_length int,
	licker_lower_speed int,
	sliver_weight decimal(10,2),
	cylinder_lower_speed int,
	draft_coeff int,
	roller_lower_speed int,
	doffer_high_speed int,
	clean_roller_lower_speed int,
	doffer_lower_speed int,
	creeling_work_time int,
	hopper_FMAX int,
	layering_work_time int,
	scraper_work_time int,
	slitting_work_time int,
	scraper_interval_time int,
	machine_belly_blowing_work_time int,
	machine_blowing_work_time int,
	machine_belly_blowing_interval_time int,
	machine_blowing_interval_time int,
	target_sliver int,
	target_cotton_layer int,
	foreign_matter_detection int,
	high_speed_draft int,
	closed_loop_intensity int,
	row_head_draft int,
	closed_weight_control_area int,
	dead_zone_length int,
	cotton_layer_gain int,
	even_lower_limit int,
	raw_material_properties int,
	even_upper_limit int,
	preset_pressure int,
	pressure_upper_limit int,
	pressure_lower_limit int,
	control_mode int,
	PRIMARY KEY ( record_id ));

create table JWF1312B_bingtiao (
	record_id bigint not null auto_increment,
	record_id_shumian bigint not null,
	machineNo int,
	record_timestamp datetime,
	leveling_switch_r int,
	leveling_range_r int,
	enlarge_times_r int,
	dead_zone_length_r int,
	leveling_limit_speed_r int,
	weight_deviation_r decimal(5,2),
	monitor_switch_r int,
	calibration_speed_r int,
	A_pct_value_r float(53),
	AS_pct_value_r float(53),
	CV_pct_value_r float(53),
	CV_pct_1m_r float(53),
	TP_pct_plus_r float(53),
	TP_pct_minus_r float(53),
	linear_factor_r int,
	zero_voltage_r int,
	scale_ratio_r int,
	A_pct_update_r int,
	A_pct_update_time_r int,
	CV_pct_update_ratio_r decimal(5,2),
	CV_pct_1m_update_ratio_r float(53),
	leveling_switch_l int,
	leveling_range_l int,
	enlarge_times_l int,
	dead_zone_length_l int,
	leveling_limit_speed_l int,
	weight_deviation_l decimal(5,2),
	monitor_switch_l int,
	calibration_speed_l int,
	A_pct_value_l float(53),
	AS_pct_value_l float(53),
	CV_pct_value_l float(53),
	CV_pct_1m_l float(53),
	TP_pct_plus_l float(53),
	TP_pct_minus_l float(53),
	linear_factor_l float(53),
	zero_voltage_l int,
	scale_ratio_l int,
	A_pct_update_l int,
	A_pct_update_time_l int,
	CV_pct_update_ratio_l decimal(5,2),
	CV_pct_1m_update_ratio_l float(53),
	breed int,
	A_numberofgears int,
	B_numberofgears int,
	J_numberofgears int,
	N_numberofgears int,
	K_numberofgears int,
	merge_sliver_count int,
	former_gauge int,
	back_gauge int,
	drafting_ratio decimal(5,2),
	acceleration_time float(53),
	deceleration_time float(53),
	op_freq decimal(7,2),
	full_load_length int,
	change_load_mode int,
	K_value_r int,
	B_value_r int,
	voltage_200um_r int,
	K_value_l int,
	B_value_l int,
	voltage_200um_l int,
	PRIMARY KEY ( record_id ));
alter table JWF1312B_bingtiao add foreign key(record_id_shumian) references JWF1211_shumuan(record_id);

create table JWF1418_cusha (
	record_id bigint not null auto_increment,
	record_id_bingtiao bigint not null,
	machineNo int,
	record_timestamp datetime,
	spindle_speed_set int,
	spindle_speed_full_yarn int,
	raw_head_speed int,
	draft_ratio decimal(9,2),
	character_coeff decimal(20,2),
	bobbin_coeff decimal(20,2),
	layer_thickness decimal(20,2),
	roving_twist decimal(20,2),
	bobbin_diameter decimal(20,2),
	fixed_length int,
	roving_quantity int,
	pressure_palm_laps int,
	winding_density decimal(20,2),
	form_length int,
	form_angle int,
	reversing_forbid int,
	intubation_position int,
	raw_head_position int,
	stop_position int,
	top_correction int,
	bottom_correction int,
	above_keel_refueling_time_interval int,
	below_keel_refueling_time_interval int,
	nozzle_filling_duration int,
	cone_top_position int,
	dolly_position int,
	take_full_yarn_above_reversing_position int,
	take_full_yarn_below_stop_position int,
	release_full_yarn_above_reversing_position int,
	release_full_yarn_below_stop_position int,
	take_black_bobbin_below_stop_position int,
	take_black_bobbin_above_reversing_position int,
	shake_position int,
	release_black_bobbin_below_stop_position int,
	release_black_bobbin_above_reversing_position int,
	stop_length int,
	return_yarn_length int,
	winding_position int,
	immediate_full_yarn_return_length int,
	advance_parking_length int,
	forbid_adjustment_coeff int,
	blow_suction_air_motor_interval_time int,
	blow_suction_air_motor_continue_time int,
	doffing_process_setting int,
	full_yarn_return_yarn_coeff int,
	full_yarn_twisting_time int,
	PRIMARY KEY ( record_id ));
alter table JWF1418_cusha add foreign key(record_id_bingtiao) references JWF1312B_bingtiao(record_id);

create table JWF1562_xisha (
	record_id bigint not null auto_increment,
	record_id_cusha bigint not null,
	record_timestamp datetime,
	machineNo int,
	spinning_specification decimal(5,2),
	rolla_initial_speed smallint,
	blower_on_spindle_on decimal(4,1),
	main_spindle_off_brake decimal(4,1),
	hypocycloid_start decimal(3,1),
	fundamental_frequency tinyint,
	spindle_number_setting smallint,
	doffing_mode_selection tinyint,
	spindle_speed_correction decimal(4,3),
	rolla_diameter tinyint,
	wharve_diameter int,
	roller_diameter smallint,
	doffing_spindle_speed smallint,
	ring_rail_drop_mspindle_off decimal(4,1),
	fixed_length_setting smallint,
	fixed_time_setting smallint,
	brake_yarn_time decimal(3,1),
	rolla_speed_correction decimal(3,2),
	spindle_pulley_diameter smallint,
	main_motor_pulley_diameter smallint,
	yarn_spindle_speed smallint,
	yarn_time decimal(4,1),
	block_delay_time decimal(4,1),
	hypocycloid_pause_time decimal(4,1),
	tubing_scratcher_inflation_time decimal(4,1),
	tubing_scratcher_deflation_time decimal(4,1),
	drip_running_time decimal(5,1),
	drip_pause_time decimal(5,1),
	blow_suction_cop_length smallint,
	frequency_setting smallint,
	roving_rationNe int,
	roving_rationG smallint,
	curve_setting_number tinyint,
	curve_call_number tinyint,
	L0 tinyint,
	L1 tinyint,
	L2 tinyint,
	L3 tinyint,
	L4 tinyint,
	L5 tinyint,
	L6 tinyint,
	L7 tinyint,
	L8 tinyint,
	L9 tinyint,
	s0 smallint,
	s1 smallint,
	s2 smallint,
	s3 smallint,
	s4 smallint,
	s5 smallint,
	s6 smallint,
	s7 smallint,
	s8 smallint,
	s9 smallint,
	compact_yarn_fan_f decimal(3,1),
	strip_machine_stop_t decimal(5,1),
	strip_machine_run_t decimal(5,1),
	blow_suction_pause_t decimal(5,1),
	pause_stop_spindle_v smallint,
	pause_start_spindle_v smallint,
	empty_delay_drop_sys decimal(5,1),
	full_delay_drop_sys_off_t decimal(5,1),
	spin_drop decimal(5,2),
	ring_rail_action decimal(5,2),
	in_yarn_pause_time decimal(5,2),
	doffing_compensation decimal(5,1),
	doffing_speed smallint,
	spin_drop_speed smallint,
	spin_rise_speed smallint,
	step_rising smallint,
	substrate_compensation smallint,
	in_yarn_position tinyint,
	full_pipe_height decimal(5,1),
	ring_rail_dropping_speed smallint,
	ring_rail_dropping_position decimal(3,1),
	pause_compensation_value decimal(2,1),
	winding_diameter decimal(4,1),
	cop_diameter decimal(4,1),
	pitch_diameter_ratio decimal(3,1),
	short_stroke decimal(4,1),
	pause_slowdown_time decimal(3,1),
	pause_accelerate_time decimal(3,1),
	base_position decimal(4,1),
	yarn_position decimal(4,1),
	cam_ratio decimal(3,1),
	pause_position tinyint,
	ring_rise_speed smallint,
	ring_rise_distance int,
	ring_rise_gap int,
	PRIMARY KEY ( record_id ));
alter table JWF1562_xisha add foreign key(record_id_cusha) references JWF1418_cusha(record_id);

create table SMARO_E_luotong (
	record_id bigint not null auto_increment,
	record_id_xisha bigint not null,
	record_timestamp datetime,
	machineNo int,
	machine_identifier int,
	machine_serial int,
	screen_saver int,
	language_setting int,
	machine_drive_lr int,
	length_unit_of_measure int,
	weight_unit_of_measure int,
	count_unit_of_measure int,
	yarn_clearer_type int,
	machine_mode int,
	sensor_negtive_pressure int,
	cleaning_fan_interval int,
	cleaning_fan_rounds int,
	tube_conveyor_method int,
	tube_conveyor_interval real,
	tube_conveyor_interval_count int,
	package_unload_belt int,
	division_amount int,
	position_amount int,
	group_amount int,
	day_of_week int,
	class_amount int,
	PRIMARY KEY ( record_id ));
alter table SMARO_E_luotong add foreign key(record_id_xisha) references JWF1562_xisha(record_id);
